#!/bin/bash

# Function to check file syntax. Currently supports: 
#    * css
#    * html
#    * js/json 
#    * php
#    * rb
#    * sh
#    * xml
#
# It also supports checking that image files (gif,jpg,png,svg) are valid through imagemagick
#
# Checkfile expects a path to a file
# Returns:
# 0 on success
# 1 on syntax check error 
# 2 for unsupported files
# 3 for files which are supported, but which the syntx checker is not installed

# Sets variable CHECK_RES to the output of the syntax check command

# JavaScript's hint takes an optional config file from /etc/syntax_checker/jshint-config.json or ~/.syntax_checker/jshint-config.json
# and a custom reporter file from /etc/syntax_checker/jshint-custom-reporter.js or ~/.syntax_checker/jshint-custom-reporter.json

# HTML tidy takes an optional config file from /etc/syntax_checker/tidy.conf or ~/.syntax_checker/tidy.conf

# Note: Echo CHECK_RES with surrounding quotes to preserve newlines
# eg. echo "$CHECK_RES"

function checkfile {

FILEPATH=$1
EXTENSION=$(echo "${FILEPATH##*.}" | tr '[A-Z]' '[a-z]')
CHECK_RES=""
RET_VAL=0

if [ -d $FILEPATH ] ; then
    EXTENSION='DIRECTORY'
fi

if [ "$2" != "" ]; then
    EXTENSION=$2
fi

if [ -f ~/.syntax_checker/PATH ]; then
    paths=$(cat ~/.syntax_checker/PATH | grep -v '#')
    for ((i=${#paths[@]}-1; i>=0; i--)); do
        export PATH="${paths[$i]}":$PATH
    done
elif [ -f /etc/syntax_checker/PATH ]; then
    paths=$(cat /etc/syntax_checker/PATH | grep -v '#')
    for ((i=${#paths[@]}-1; i>=0; i--)); do
        export PATH="${paths[$i]}":$PATH
    done
fi

case "$EXTENSION" in
    css)
        # https://github.com/stubbornella/csslint
        # Ignore warnings
        which csslint 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="csslint not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(csslint --quiet --format=compact $FILEPATH 2>&1 | grep -v Warning)
            if [ "$CHECK_RES" != "" ] ; then
                RET_VAL=1
            fi
        fi;;
    DIRECTORY)
        # Submodules in git show up as directories
        CHECK_RES=''
        RET_VAL=0
	;;
    gif|jpg|png|svg)
        which identify 2>&1 >/dev/null
        if [ "$?" -ne 0 ]; then
            CHECK_RES="identify (imagemagick) not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(identify $FILEPATH 2>&1)
            if [ "$?" -ne "0" ]; then 
                RET_VAL=1
            else
                CHECK_RES=""
            fi
        fi;;
    html|htm)
        which tidy 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="tidy not found in path"
            RET_VAL=3
        else

            if [ -f ~/.syntax_checker/tidy.conf ]; then
                CONF="-config "~/.syntax_checker/tidy.conf
            elif [ -f /etc/syntax_checker/tidy.conf ]; then
                CONF="-config "/etc/syntax_checker/tidy.conf
            else
                CONF=""
            fi

            CHECK_RES=$(tidy -e -q $CONF $FILEPATH 2>&1)
            exitval=$?
            if [ "$exitval" -ne "0" ]; then
                RET_VAL=1
            fi
        fi
        ;;
    js|json)
        # http://www.jshint.com/
        HINTBIN=$(which jshint);
        if [ "$HINTBIN" == "" ]; then
            HINTBIN=$(which hint);
        fi

        if [ "$HINTBIN" = "" ]; then
            CHECK_RES="hint not found in path"
            RET_VAL=3
        else
            if [ -f ~/.syntax_checker/jshint-config.json ]; then
                HINTFILE="--config "~/.syntax_checker/jshint-config.json
            elif [ -f /etc/syntax_checker/jshint-config.json ]; then
                HINTFILE="--config "/etc/syntax_checker/jshint-config.json
            else
                HINTFILE=""
            fi

            if [ -f ~/.syntax_checker/jshint-custom-reporter.js ]; then
                REPORTER="--reporter "~/.syntax_checker/jshint-custom-reporter.js
            elif [ -f /etc/syntax_checker/jshint-custom-reporter.js ]; then
                REPORTER="--reporter "/etc/syntax_checker/jshint-custom-reporter.js
            else
                REPORTER=""
            fi

            CHECK_RES=$($HINTBIN $HINTFILE $REPORTER $FILEPATH 2>&1)
            if [ "$CHECK_RES" != "" ]; then
                RET_VAL=1
            fi
        fi;;
    php)
        which php 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="php program not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(php -l $FILEPATH 2>&1 | grep -v 'No syntax errors detected')
            if [ "$CHECK_RES" != "" ] ; then
                RET_VAL=1
            fi
        fi;; 
    py)

        which pylint >&1 >/dev/null
        if [ "$?" -eq "0" ]; then



            if [ -f ~/.pylintrc ]; then
                RCFILE="--rcfile "~/.pylintrc
            elif [ -f ~/.syntax_checker/pylintrc ]; then 
                RCFILE="--rcfile "~/.syntax_checker/pylintrc 
            elif [ -f /etc/syntax_checker/pylintrc ]; then 
                RCFILE="--rcfile "/etc/syntax_checker/pylintrc 
            else
                RCFILE=""
            fi

            CHECK_RES=$(pylint -r n $RCFILE $FILEPATH)
            exitval=$?
            if [ "$exitval" -ne "0" ]; then
                CHECK_RES=$(pylint -r n $RCFILE $FILEPATH | grep [EWC])
                RET_VAL=1
            else
                CHECK_RES=""
            fi
        else
            which python 2>&1 >/dev/null
            if [ "$?" -ne "0" ]; then
                CHECK_RES="python program not found in path"
                RET_VAL=3
            else
                if [ !-f $(basename $FILEPATH).pyc ]; then
                    REMOVE_PYC = 1;
                fi

                CHECK_RES=$(python -m py_compile $FILEPATH)
                exitval=$?
                if [ "$exitval" -ne "0" ]; then
                    RET_VAL=1
                else
                    CHECK_RES=""
                fi

                if [ "$REMOVE_PYC" -eq "1" ]; then
                    rm $(basename $FILEPATH).pyc
                fi
            fi
        fi
        ;;
    rb)
        which ruby 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="ruby not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(ruby -c $FILEPATH 2>&1)
            exitval=$?
            if [ "$exitval" -ne "0" ]; then
                RET_VAL=1
            else
                CHECK_RES=""
            fi
        fi;;
    sh)
        which bash 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="bash not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(bash -n $FILEPATH 2>&1)
            exitval=$?
            if [ "$exitval" -ne "0" ]; then
                RET_VAL=1
            fi
        fi;;
    xml)
        # http://xmlsoft.org/xmllint.html
        which xmllint 2>&1 >/dev/null
        if [ "$?" -ne "0" ]; then
            CHECK_RES="xmllint not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(xmllint $FILEPATH >/dev/null 2>&1)
            if [ "$?" -ne "0" ]; then
                CHECK_RES=$(xmllint $FILEPATH 2>&1 | grep -v compiled)
                RET_VAL=1
            fi
        fi;;
    sql)
        # https://github.com/markdrago/pgsanity
        # Specific to postgres, but others may benefit too
        which pgsanity 2>&1 >/dev/null
        if [ "$?" -ne 0 ]; then
            CHECK_RES="pgsanity not found in path"
            RET_VAL=3
        else
            CHECK_RES=$(pgsanity $FILEPATH)
            if [ "$?" -ne "0" ]; then
                RET_VAL=1
            fi
        fi;;
    txt)
        file --mime-type $FILEPATH | grep 'text'
        if [ "$?" -ne "0" ]; then
            CHECK_RES=$(file --mime-type $FILEPATH | grep -v 'text')
            RET_VAL=1
        fi;;
    *)
        CHECK_RES="$EXTENSION not found in syntax check list"
        RET_VAL=2
esac

echo -n "$CHECK_RES"
return $RET_VAL
}
